sudo: false
language: rust
before_script:
- curl -LSfs https://japaric.github.io/trust/install.sh | sh -s -- --git cobalt-org/cobalt.rs
  --crate cobalt --force --target x86_64-unknown-linux-gnu --tag v0.12.1
- export PATH="$PATH:~/.cargo/bin"
script:
- cobalt build && (find . -type f | grep 'html' | xargs sed -i.bak  -e 's/^[ \t]*//g' -e '/^$/d')
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "${GH_TOKEN}"
  local_dir: _site
  target_branch: master
  on:
    branch: source
env:
  global:
  - secure: Nrl8es/ye+jRPv9MP2uuEMkcwPR5/DFygcao4jzG5E5Q4y5lsyG/eApneDzIFPXolNMUkizOotAefV26yGhoRPPeNL7YC0P63vtDaK86vy7SlLsd76Lfm8oR+pqQUHEurEaZ2bzXIPGmDViRAT1JmmPRhIqkkeTucwM2Bj/fRT34VJYBvY72W5aA9lBKy0tLIGT3b6IFX7r0atmAolyV6LtFRoYsIYexOgSAvN+bAh2HwuNkoL94UWa6r9Z9U5b5XORnJutUP7a1bvZ6LEuN4ZBWMTPhq882EBHL0qu7XGAzeL5X9bkZPpOQ5a/JFAwrm3rGd0nDzZUaeXmUDmP1r8+n0svgJsCCyJeNTQ5I4O3X9+bAVVTzYf+KQY/hWAV1YzhpK94eNsDGGISGjB80N82fVxjVDRP2ZGZC1vbgV8Bh+JAeiUZGlbCSvWFr/LjlkbVLEw5+N/BAjEaAuw7cmHvJGYJZJCb6gkSxO+QAWfKo4EPIKQ6H+PABs3r1JeBnwoqECXT0lrZ0nhTaxPOf0DGn/XihfVDgaaJkbEr97wg0d9a4/TOg+eSkFy9GcJjV7zOBADt/1HG+x+9kPcSUui2DhyQSpUm8E3wmpERnCwP8ztUsQRgl+/8KbtF3GxGbmZTprShRLmKEJfAZO4R3otBiKUXw8WIZr+4MdNU0wdI=
  - secure: HfVnXi/JfSOlA1u6bHzirxvcq3svO9zxOf1t7oursHPI3oUkacnx73/m0iXSXOTH/7XlS6EFlfWvlr24RY88aDb/SPRaZWZ3KLbnTMEY7s9lmnmkacpB8noX7ExUGbAy0QBwrAL3M+E5MMwpGupb2elur7TVuh7q+yjLLsIvtY/Y6sQ3GCWgOyU24UGInievmXUGrB3g9Kq7w3BRthM01EoHCYv9prnDczhxGi92k4LVBohMzqsaS2BtQitwhjyZhkRFWcUJ63uOWPgCufPRF9LajsLiK1kbXUAPmzw0lZAIk3yFwVOYpcHR6DLnBdPEkFVlnTFK9X6Q0eBU8dabuxBEoxtVQ/P/OJp93oFi/4cm/Jmg/FJ0O5vzdRwA7vbs+nPDofHmdwvU64YZb4ADWfwgosWAb5c6PaQTsa29hDepAnzrKuqWFzEFCChdjsQZ4VzgtCCymLLWikGCs1E14LKyewNqq201AS7gKEnQH0IVMhwdUskY7yg+fHXgwqelRP1xr+4oIHAM6V1/3XKScFasPZdcxCzTqS8DuqszrzvjrZ+jjDmmBgZWAWy42iko23JfLd9SDhIpoaBLAHaAZGQLz6RG9e4uOhyjZAhzarnBxfPl0KHIj6FXQgeuIjfKcR4wolFXokA/5v7e6kk7IRDAWgIeV93XjYg27NwD2Ng=
